version: "3.8"

networks:
  zeroAgencyTask:
    name: zeroAgencyTask

services:
  server:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zeroAgencyTask

  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_BASE}
      POSTGRES_SSL_MODE: ${PG_SSL_MODE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - zeroAgencyTask
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  