version: "3.8"

networks:
  zeroAgencyTask:
    name: zeroAgencyTask

services:
#  server:
#    image: golang:alpine3.18
#    working_dir: /bin/cmd/app
#    env_file: 
#      - .env
#    volumes: 
#      - .:/bin
#    command: go run main.go
#    ports:
#      - ${SERVER_PORT}:${SERVER_PORT}
#    depends_on:
#      - postgres
#    networks:
#      - zeroAgencyTask

  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_BASE}
      POSTGRES_SSL_MODE: ${PG_SSL_MODE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - zeroAgencyTask
  